services:
  - type: web
    name: todo-backend
    env: docker
    dockerfilePath: backend/Dockerfile
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: todo-db
          property: connectionString
  - type: web
    name: todo-frontend
    env: docker
    dockerfilePath: frontend/Dockerfile
    plan: free
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://todo-backend.onrender.com
databases:
  - name: todo-db
    plan: free
    region: oregon
